spring.application.name=chat-app
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username= hayata
spring.datasource.password= 35320422Sora
spring.flyway.baselineOnMigrate=true